version: "3.7"

volumes:
  dev-db:

services:
  gj-db:
    image: postgres:12.1-alpine
    volumes:
      - "dev-db:/var/lib/postgresql/data"

  gj-service:
    build:
      context: ./gratitude_journal_service
      target: base
    command: >
      bash -c "
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - gj-db
    environment:
      DB_HOST: gj-db
      DB_PORT: 5432
      DEV_MODE: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./gratitude_journal_service:/server

  gj-ui:
    build:
      context: ./gratitude-journal-web
      target: base
    command: "npm start"
    depends_on:
      - gj-service
      - gj-db
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./gratitude-journal-web/src:/app/src
      - ./gratitude-journal-web/config:/app/config
      - ./gratitude-journal-web/public:/app/public
      - ./gratitude-journal-web/scripts:/app/scripts
      - ./gratitude-journal-web/.env.development.local:/app/.env.development.local

  gj-ui-test:
    build:
      context: ./gratitude-journal-web
      target: base
    command: "npm test"
    volumes:
      - ./gratitude-journal-web/src:/app/src
      - ./gratitude-journal-web/config:/app/config
      - ./gratitude-journal-web/scripts:/app/scripts
