version: "3.7"
volumes:
  prod-db:
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - "prod-db:/var/lib/postgresql/data"

  service:
    depends_on:
      - db

  ui:
    depends_on:
      - db
      - service
    environment:
      GRAPHQL_FORWARD_TO: service:8000
