version: "3.7"
volumes:
  prod-db:
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - "prod-db:/var/lib/postgresql/data"

  service:
    depends_on:
      - db
    environment:
      SECRET_KEY_FILE: /run/secrets/service_key
    secrets:
      - service_key

  ui:
    depends_on:
      - db
      - service
    environment:
      GRAPHQL_FORWARD_TO: service:8000

secrets:
  service_key:
    file: .secrets/secret-key
