version: "3.7"

volumes:
  dev-db:

services:
  db:
    volumes:
      - "dev-db:/var/lib/postgresql/data"

  test-db:
    image: postgres:12.1-alpine
    
  service-test-refresh-db:
    build:
      context: ./gratitude_journal_service
      target: base
    command: >
      bash -c "
        python manage.py flush --no-input &&
        python manage.py migrate &&
        python manage.py loaddata users.yaml entries.yaml
      "
    environment:
      DB_HOST: test-db
      DB_PORT: 5432
      DEV_MODE: 'true'
    image: gj-service:dev
    volumes:
      - ./gratitude_journal_service:/server

  service-test-e2e:
    build:
      context: ./gratitude_journal_service
      target: base
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - test-db
    environment:
      DB_HOST: test-db
      DB_PORT: 5432
      DEV_MODE: 'true'
    image: gj-service:dev
    ports:
      - "8000:8000"
    volumes:
      - ./gratitude_journal_service:/server

  service-test:
    build:
      context: ./gratitude_journal_service
      target: base
    command: python manage.py test
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DEV_MODE: "true"
    image: gj-service:dev
    volumes:
      - ./gratitude_journal_service:/server

  service:
    build:
      context: ./gratitude_journal_service
      target: base
    depends_on:
      - db
    environment:
      DEV_MODE: "true"
      LOG_LEVEL: debug
    image: gj-service:dev
    ports:
      - "8000:8000"
    volumes:
      - ./gratitude_journal_service:/server

  ui-test:
    build:
      context: ./gratitude-journal-web
    command: "npm start"
    depends_on:
      - service-test-e2e
    environment:
      PORT: 3000
      GRAPHQL_FORWARD_TO: service-test-e2e:8000
    image: gj-web:build
    ports:
      - "3000:3000"

  ui:
    build:
      context: ./gratitude-journal-web
      target: base
    depends_on:
      - db
      - service
    image: gj-web:dev
    volumes:
      - ./gratitude-journal-web/src:/app/src
      - ./gratitude-journal-web/config:/app/config
      - ./gratitude-journal-web/public:/app/public
      - ./gratitude-journal-web/scripts:/app/scripts
      - ./gratitude-journal-web/.env.development.local:/app/.env.development.local
