version: "3.7"
services:
  db:
    image: postgres:12.1-alpine

  service:
    build:
      context: ./gratitude_journal_service
    environment:
      DB_HOST: db
      DB_PORT: 5432
    command: >
      bash -c "
        python manage.py check --deploy &&
        python manage.py migrate &&
        gunicorn --workers=2 --threads=4 --worker-class=gthread --log-file=- --bind 0.0.0.0:8000 gratitude_journal_service.wsgi
      "
    image: gj-service:build

  ui:
    build:
      context: ./gratitude-journal-web
    command: "npm start"
    environment:
      PORT: 3000
    image: gj-web:build
    ports:
      - "3000:3000"
