version: "3.7"
services:
  gj-db:
    image: postgres:12.1-alpine
  gj-service:
    image: gj-service:latest
    depends_on:
      - gj-db
  gj-ui:
    image: gj-ui:latest
    depends_on:
      - gj-db
      - gj-service

