version: "3.7"

volumes:
  dev-db:

services:
  db:
    volumes:
      - "dev-db:/var/lib/postgresql/data"

  service-test:
    build:
      context: ./gratitude_journal_service
      target: base
    command: python manage.py test
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DEV_MODE: "true"
    volumes:
      - ./gratitude_journal_service:/server

  service:
    build:
      context: ./gratitude_journal_service
      target: base
    depends_on:
      - db
    environment:
      DEV_MODE: "true"
      LOG_LEVEL: debug
    ports:
      - "8000:8000"
    volumes:
      - ./gratitude_journal_service:/server

  ui-test:
    build:
      context: ./gratitude-journal-web
      target: base
    command: "npm test"
    volumes:
      - ./gratitude-journal-web/src:/app/src
      - ./gratitude-journal-web/config:/app/config
      - ./gratitude-journal-web/scripts:/app/scripts

  ui:
    build:
      context: ./gratitude-journal-web
      target: base
    depends_on:
      - db
      - service
    volumes:
      - ./gratitude-journal-web/src:/app/src
      - ./gratitude-journal-web/config:/app/config
      - ./gratitude-journal-web/public:/app/public
      - ./gratitude-journal-web/scripts:/app/scripts
      - ./gratitude-journal-web/.env.development.local:/app/.env.development.local
