name: CI

on: [push]

jobs:   
  service-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run backend tests
        run: docker-compose run service-test
  
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup environment
        run: docker-compose run --service-ports --detach ui
      - name: Verify running docker containers
        run: docker ps -a
      - name: Install and run cypress tests
        uses: cypress-io/github-action@v1
      - name: Save failure snapshots as artifact
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Save test videos as artifact
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
