name: CI

on: [push]

jobs:
  service-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker images
        run: docker-compose build
      - name: Run backend tests
        run: docker-compose run service-test
      - name: Cleaunp
        if: always()
        run: docker-compose down
  
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker images
        run: docker-compose build
      - name: Setup environment
        run: docker-compose run --service-ports --detach ui
      - uses: cypress-io/github-action@v1
        with:
          headless: true
      - name: Cleanup
        if: always()
        run: docker-compose down
