name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker images
        run: docker-compose build
        
  service-tests:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v1
      - name: Run backend tests
        run: docker-compose run service-test
  
  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v1
      - name: Setup environment
        run: docker-compose run --service-ports --detach ui
      - uses: cypress-io/github-action@v1
        with:
          headless: true
          
  cleanup:
    runs-on: ubuntu-latest
    needs:
      - service-tests
      - e2e-tests
    if: always()
    steps:
      - name: Cleanup up docker containers
        run: docker-compose down
